services:
  db:
    image: postgres:16
    container_name: abd
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: evidenta
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./scripts/init_database.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./database:/scripts:ro

  scheduler:
    image: postgres:16
    container_name: scheduler
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: evidenta
    volumes:
      - ./sidecar/backups:/backups
      - ./sidecar/scheduler.sh:/scheduler.sh
    entrypoint: ["/bin/bash", "/scheduler.sh"]

volumes:
  pg_data: